require:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - '**/Gemfile'
    - '**/Gemfile.lock'
    - 'db/**/*'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'server.rb'

  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Metrics/MethodLength:
  Enabled: false