version: '3.8'

services:
  db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snippet_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-cntrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/team_development_1
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: snippet_db

volumes:
  db_data:
